development:
    cloudinary_cloud_name: <%= ENV["CLOUDINARY_CLOUD_NAME"] %>
    cloudinary_api_key: <%= ENV["CLOUDINARY_API_KEY"] %>
    cloudinary_api_secret: <%= ENV["CLOUDINARY_API_SECRET"] %>
    stripe_secret_key: 'sk_test_hbZNcGn0cFrd1zHZww9MOeTP00ZYK1U0ER'
    stripe_publishable_key: 'pk_test_kAJhEXeRMfMf4Q5Rqp2R1lAf00wS1pNqC0'

test:
    cloudinary_cloud_name: <%= ENV["CLOUDINARY_CLOUD_NAME"] %>
    cloudinary_api_key: <%= ENV["CLOUDINARY_API_KEY"] %>
    cloudinary_api_secret: <%= ENV["CLOUDINARY_API_SECRET"] %>
production:
    cloudinary_cloud_name: <%= ENV["CLOUDINARY_CLOUD_NAME"] %>
    cloudinary_api_key: <%= ENV["CLOUDINARY_API_KEY"] %>
    cloudinary_api_secret: <%= ENV["CLOUDINARY_API_SECRET"] %>
    stripe_secret_key: 'sk_live_aLvPhyGtUwlLSHvms3KhCdrL'
    stripe_publishable_key: 'pk_live_nbTqsm8Gg0eHGrQVRbWnjlyN'
