development:
    cloudinary_cloud_name: <%= ENV["CLOUDINARY_CLOUD_NAME"] %>
    cloudinary_api_key: <%= ENV["CLOUDINARY_API_KEY"] %>
    cloudinary_api_secret: <%= ENV["CLOUDINARY_API_SECRET"] %>
    stripe_secret_key: <%= ENV["STRIPE_SECRET_KEY"] %>
    stripe_publishable_key: <%= ENV["STRIPE_PUBLISHABLE_KEY"] %>

test:
    cloudinary_cloud_name: <%= ENV["CLOUDINARY_CLOUD_NAME"] %>
    cloudinary_api_key: <%= ENV["CLOUDINARY_API_KEY"] %>
    cloudinary_api_secret: <%= ENV["CLOUDINARY_API_SECRET"] %>
production:
    cloudinary_cloud_name: <%= ENV["CLOUDINARY_CLOUD_NAME"] %>
    cloudinary_api_key: <%= ENV["CLOUDINARY_API_KEY"] %>
    cloudinary_api_secret: <%= ENV["CLOUDINARY_API_SECRET"] %>
